apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  selector:
     matchLabels:
       app: api-server
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api-server
    spec:
      hostNetwork: true
      containers:
        - image: sentiment-api
          imagePullPolicy: Never
          name: api-server
          env:
            - name: LOGIC_SERVER
              value: "http://logic-server"
          ports:
            - containerPort: 7000