apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    app: web-server
spec:
  containers:
    - image: sentiment-web
      imagePullPolicy: Never
      name: web-server
      ports:
        - containerPort: 9000